# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Build and upload to TestFlight using App Store Connect API key"
  lane :beta do

    app_store_connect_api_key()
    increment_build_number(
      build_number: app_store_build_number + 1,
      xcodeproj: "MIAapp.xcodeproj"
    )
    build_app(scheme: "MIAapp")
    upload_to_testflight()
  end
end